### ISSUE TITLE
fatal error: atlas_package/tags_dynParamsConfig.h

### ISSUE THREAD

**Issue by avinashGonsalves** [tudo-cni-atlas/atlas_config_example#1]
[ 89%] Building CXX object atlas_rtls/atlas_fast/CMakeFiles/atlas_fast_node.dir/src/Scheduler.cpp.o
/home/avinash/UWB/atlas_rtls/catkin_workspace/src/atlas_rtls/atlas_fast/src/Scheduler.cpp:10:10: fatal error: atlas_package/tags_dynParamsConfig.h: No such file or directory
 #include <atlas_package/tags_dynParamsConfig.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/avinash/UWB/atlas_rtls/catkin_workspace/src/atlas_rtls/atlas_fast/src/main.cpp:17:0:
/home/avinash/UWB/atlas_rtls/catkin_workspace/src/atlas_rtls/atlas_fast/include/atlas_fast/Scheduler.h:104:22: error: ‘atlas_package’ has not been declared
     void getTagParam(atlas_package::tags_dynParamsConfig &config);

**Comment by tudoetknjt** [comment]
The issue should be fixed now (it is in the atlas_rtls repo). The correct path should have been:
`#include <atlas_fast/tags_dynParamsConfig.h>`

Thanks for the note!

**Comment by avinashGonsalves** [comment]
Build is successful now. 
But how do i run the example? 
Getting the following error:

atlas_rtls$ roslaunch launch/config.launch
... logging to /home/avinash/.ros/log/fd7a6224-cae2-11e8-a8b3-08002756816e/roslaunch-avinash-vbox-5793.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Resource not found: atlas_config_flw
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/opt/ros/melodic/share
The traceback for the exception was written to the log file
avinash@avinash-vbox:~/UWB/atlas_rtls$

**Comment by tudoetknjt** [comment]
Ok. I forgot to write sourcing devel/setup.bash
Also the roslaunch paths should be fixed now to atlas_config_example.

**Comment by avinashGonsalves** [comment]
I just did a pull, i think you missed one change
/home/avinash/UWB/atlas_rtls/catkin_workspace/src/atlas_rtls/atlas_fast/src/Scheduler.cpp: In constructor ‘Tag::Tag(uint64_t, uint64_t)’:
/home/avinash/UWB/atlas_rtls/catkin_workspace/src/atlas_rtls/atlas_fast/src/Scheduler.cpp:119:66: **error: ‘atlas_package’ was not declared in this scope**

Also, this error during ros launch
avinash@avinash-vbox:~/UWB/atlas_rtls/catkin_workspace$ roslaunch atlas_config_example config.launch
... logging to /home/avinash/.ros/log/fd7a6224-cae2-11e8-a8b3-08002756816e/roslaunch-avinash-vbox-6904.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

RLException: error loading <rosparam> tag: 
	file does not exist **[/home/avinash/UWB/atlas_rtls/catkin_workspace/src/atlas_config_example/config/trajectory.yaml]**
XML is <rosparam command="load" file="$(find atlas_config_example)/config/trajectory.yaml" ns="atlas/"/>

**Comment by tudoetknjt** [comment]
True... The trajectory.yaml is not required anymore and is removed from the launch file.

**Comment by avinashGonsalves** [comment]
One more Visualizer Error:

avinash@avinash-vbox:~/UWB/atlas_rtls/catkin_workspace$ source devel/setup.bash
avinash@avinash-vbox:~/UWB/atlas_rtls/catkin_workspace$ roslaunch atlas_config_example visualizer.launch
... logging to /home/avinash/.ros/log/fd7a6224-cae2-11e8-a8b3-08002756816e/roslaunch-avinash-vbox-11602.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

resource not found: atlas_config_flw
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/avinash/UWB/atlas_rtls/catkin_workspace/src
ROS path [2]=/opt/ros/melodic/share None
when processing file: /home/avinash/UWB/atlas_rtls/catkin_workspace/src/atlas_config_example/visualization/innolab.urdf.xacro
RLException: Invalid <param> tag: Cannot load command parameter [lab_description]: command [/opt/ros/melodic/lib/xacro/xacro /home/avinash/UWB/atlas_rtls/catkin_workspace/src/atlas_config_example/visualization/innolab.urdf.xacro] returned with code [2]. 

Param xml is <param command="$(find xacro)/xacro $(find atlas_config_example)/visualization/innolab.urdf.xacro" name="lab_description"/>
The traceback for the exception was written to the log file

**Comment by tudoetknjt** [comment]
The path should be fixed now. :)

**Comment by avinashGonsalves** [comment]
Cool Everything works smooth now. 
Btw when can you share the firmware for this?

**Comment by tudoetknjt** [comment]
Cool, thanks for trying the example!
The plan is to share the firmware once academic peer review of an associated research paper is finished.
